default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 12345
  timeout: 5000

development:
  <<: *default
  database: desafio-app
test:
  <<: *default
  database: desafio-app

production:
  <<: *default
  database: desafio-app